// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/auliardana/fleetify-test/internal/repository (interfaces: DepartementRepository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/auliardana/fleetify-test/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockDepartementRepository is a mock of DepartementRepository interface.
type MockDepartementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartementRepositoryMockRecorder
}

// MockDepartementRepositoryMockRecorder is the mock recorder for MockDepartementRepository.
type MockDepartementRepositoryMockRecorder struct {
	mock *MockDepartementRepository
}

// NewMockDepartementRepository creates a new mock instance.
func NewMockDepartementRepository(ctrl *gomock.Controller) *MockDepartementRepository {
	mock := &MockDepartementRepository{ctrl: ctrl}
	mock.recorder = &MockDepartementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartementRepository) EXPECT() *MockDepartementRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepartementRepository) Create(arg0 context.Context, arg1 *entity.Departement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDepartementRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartementRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDepartementRepository) Delete(arg0 context.Context, arg1 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartementRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartementRepository)(nil).Delete), arg0, arg1)
}

// FindById mocks base method.
func (m *MockDepartementRepository) FindById(arg0 context.Context, arg1 interface{}) (*entity.Departement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0, arg1)
	ret0, _ := ret[0].(*entity.Departement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDepartementRepositoryMockRecorder) FindById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDepartementRepository)(nil).FindById), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockDepartementRepository) GetAll(arg0 context.Context) ([]entity.Departement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]entity.Departement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDepartementRepositoryMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDepartementRepository)(nil).GetAll), arg0)
}

// Update mocks base method.
func (m *MockDepartementRepository) Update(arg0 context.Context, arg1 *entity.Departement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDepartementRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartementRepository)(nil).Update), arg0, arg1)
}
