// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/auliardana/fleetify-test/internal/repository (interfaces: DepartementRepository)
//
// Generated by this command:
//
//	mockgen -package mock -destination test/mock/departement_repository__mock.go github.com/auliardana/fleetify-test/internal/repository DepartementRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/auliardana/fleetify-test/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDepartementRepository is a mock of DepartementRepository interface.
type MockDepartementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartementRepositoryMockRecorder
	isgomock struct{}
}

// MockDepartementRepositoryMockRecorder is the mock recorder for MockDepartementRepository.
type MockDepartementRepositoryMockRecorder struct {
	mock *MockDepartementRepository
}

// NewMockDepartementRepository creates a new mock instance.
func NewMockDepartementRepository(ctrl *gomock.Controller) *MockDepartementRepository {
	mock := &MockDepartementRepository{ctrl: ctrl}
	mock.recorder = &MockDepartementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartementRepository) EXPECT() *MockDepartementRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepartementRepository) Create(ctx context.Context, entity *entity.Departement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDepartementRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartementRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockDepartementRepository) Delete(ctx context.Context, id any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartementRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartementRepository)(nil).Delete), ctx, id)
}

// FindById mocks base method.
func (m *MockDepartementRepository) FindById(ctx context.Context, id any) (*entity.Departement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*entity.Departement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDepartementRepositoryMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDepartementRepository)(nil).FindById), ctx, id)
}

// GetAll mocks base method.
func (m *MockDepartementRepository) GetAll(ctx context.Context) ([]entity.Departement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]entity.Departement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDepartementRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDepartementRepository)(nil).GetAll), ctx)
}

// Update mocks base method.
func (m *MockDepartementRepository) Update(ctx context.Context, entity *entity.Departement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDepartementRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartementRepository)(nil).Update), ctx, entity)
}
