// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/auliardana/fleetify-test/internal/config"
	"github.com/auliardana/fleetify-test/internal/delivery/http/handler"
	"github.com/auliardana/fleetify-test/internal/delivery/http/route"
	"github.com/auliardana/fleetify-test/internal/repository"
	"github.com/auliardana/fleetify-test/internal/service"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeServer() *gin.Engine {
	viper := config.LoadConfig()
	logger := config.NewLogger(viper)
	db := config.NewDatabase(viper, logger)
	employeeRepository := repository.NewEmployeeRepository(logger, db)
	employeeService := service.NewEmployeeService(employeeRepository, logger)
	validate := config.NewValidator()
	employeeHandler := handler.NewEmployeeHandler(employeeService, logger, validate)
	departementRepository := repository.NewDepartementRepository(logger, db)
	departementService := service.NewDepartementService(departementRepository, logger)
	departementHandler := handler.NewDepartementHandler(departementService, logger, validate)
	attendanceRepository := repository.NewAttendanceRepository(logger, db)
	attendanceHistoryRepository := repository.NewAttendanceHistoryRepository(logger, db)
	attendanceService := service.NewAttendanceService(attendanceRepository, attendanceHistoryRepository, logger)
	attendanceHandler := handler.NewAttendanceHandler(attendanceService, logger, validate)
	attendanceHistoryService := service.NewAttendanceHistoryService(attendanceHistoryRepository, logger)
	attendanceHistoryHandler := handler.NewAttendanceHistoryHandler(attendanceHistoryService, logger, validate)
	configRoute := route.NewRoute(employeeHandler, departementHandler, attendanceHandler, attendanceHistoryHandler)
	engine := config.NewApp(configRoute)
	return engine
}

// injector.go:

var configSet = wire.NewSet(config.LoadConfig, config.NewLogger, config.NewDatabase, config.NewValidator)

var repositorySet = wire.NewSet(repository.NewEmployeeRepository, repository.NewDepartementRepository, repository.NewAttendanceRepository, repository.NewAttendanceHistoryRepository)

var serviceSet = wire.NewSet(service.NewEmployeeService, service.NewDepartementService, service.NewAttendanceService, service.NewAttendanceHistoryService)

var handlerSet = wire.NewSet(handler.NewEmployeeHandler, handler.NewDepartementHandler, handler.NewAttendanceHandler, handler.NewAttendanceHistoryHandler)
